Repository googleapis/python-data-qna, pull requests merged in 2020-12, with the labels that each got.

#4 chore: add `generatedFiles` to synth metadata
  google/cloud/dataqna_v1alpha/__init__.py
  synth.metadata
Labels: api: dataqna, cla: yes, context: none

#3 docs(python): update intersphinx for grpc and auth
  docs/conf.py
  synth.metadata
Labels: api: dataqna, cla: yes, context: full

#8 test: give filesystem paths to pytest-cov
  .pre-commit-config.yaml
  google/cloud/dataqna_v1alpha/__init__.py
  noxfile.py
  synth.metadata
Labels: api: dataqna, cla: yes, context: partial

#6 docs: add allowlist warning to README
  README.rst
  docs/README.rst
Labels: api: dataqna, cla: yes

#11 docs: updating access form to point to short URL
  README.rst
Labels: api: dataqna, cla: yes
