Repository googleapis/python-data-qna, pull requests merged in 2021-04, with the labels that each got.

#27 chore: update pycqa/flake8 dependency, rename for build cop bot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
  .pre-commit-config.yaml
  google/cloud/dataqna_v1alpha/__init__.py
  synth.metadata
Labels: api: dataqna, automerge, cla: yes, context: none

#37 chore: use `gcp-sphinx-docfx-yaml`
  noxfile.py
Labels: api: dataqna, cla: yes

#39 chore: add yoshi to CODEOWNERS
  .github/CODEOWNERS
Labels: api: dataqna, automerge, cla: yes, kokoro:force-run, kokoro:run
